import type { Project } from './types';

export const initialProjects: Project[] = [
  {
    id: '1',
    businessType: '임대',
    siteName: '울산다운3차',
    highlighted: false,
    designVE: { status: '기착공' },
    basicPlan: { date: '20.07.30' },
    archReview: { date: '21.07.23' },
    unitConfirm: { status: '기획정' },
    bizApproval: { date: '22.12.12' },
    designShare: { date: '26.02.09' },
    constructionStart: '26.02.06',
  },
  {
    id: '2',
    businessType: '자체',
    siteName: '여수소제(4BL시공)',
    highlighted: false,
    designVE: { status: '착공임박' },
    basicPlan: { date: '24.02.19' },
    archReview: { date: '25.04.02' },
    unitConfirm: { date: '25.12.12' },
    bizApproval: { date: '25.12.12' },
    designShare: { date: '26.04.27' },
    constructionStart: '26.03.27',
  },
  {
    id: '3',
    businessType: '자체',
    siteName: '고양 창릉',
    highlighted: false,
    designVE: { status: '착공임박' },
    basicPlan: { date: '25.05.29' },
    archReview: { date: '25.11.17' },
    unitConfirm: { date: '25.12.01' },
    bizApproval: { date: '26.01.15' },
    designShare: { date: '26.03.30' },
    constructionStart: '26.03.31',
  },
  {
    id: '4',
    businessType: '자체',
    siteName: '평택 고덕1차 36BL',
    highlighted: false,
    designVE: { status: '착공임박' },
    basicPlan: { date: '24.10.17' },
    archReview: { date: '25.05.27' },
    unitConfirm: { date: '25.07.25' },
    bizApproval: { date: '25.11.25' },
    designShare: { date: '26.03.23' },
    constructionStart: '26.03.31',
  },
  {
    id: '5',
    businessType: '민간',
    siteName: '강릉 송정',
    highlighted: false,
    designVE: { status: '착공임박' },
    basicPlan: {},
    archReview: { date: '23.04.19' },
    unitConfirm: { date: '26.02.15' },
    bizApproval: { date: '26.03.13' },
    designShare: { date: '26.03.16' },
    constructionStart: '26.03.31',
  },
  {
    id: '6',
    businessType: '자체',
    siteName: '평택 고덕2차 33BL',
    highlighted: false,
    designVE: { status: '인허가 진행중' },
    basicPlan: { date: '24.10.17' },
    archReview: { date: '25.05.27' },
    unitConfirm: { date: '25.07.25' },
    bizApproval: { date: '25.11.25' },
    designShare: { date: '26.04.27' },
    constructionStart: '26.06.30',
  },
  {
    id: '7',
    businessType: '자체',
    siteName: '세종3차 S-2 S-1BL',
    highlighted: false,
    designVE: { status: '인허가 진행중' },
    basicPlan: { date: '25.11.20' },
    archReview: { date: '24.10.23' },
    unitConfirm: { date: '26.02.01' },
    bizApproval: { date: '26.03.13' },
    designShare: { date: '26.04.27' },
    constructionStart: '26.06.30',
  },
  {
    id: '8',
    businessType: '자체',
    siteName: '광주 임동',
    highlighted: false,
    designVE: { status: '인허가 진행중' },
    basicPlan: { date: '24.11.07' },
    archReview: { date: '24.12.17' },
    unitConfirm: { date: '26.02.27' },
    bizApproval: { date: '25.06.19' },
    designShare: { date: '26.04.27' },
    constructionStart: '26.06.30',
  },
  {
    id: '9',
    businessType: '공모',
    siteName: '의정부 법조',
    highlighted: false,
    designVE: { status: '인허가 진행중' },
    basicPlan: { date: '25.05.29' },
    archReview: { date: '25.11.17' },
    unitConfirm: { date: '25.12.01' },
    bizApproval: { date: '25.12.26' },
    designShare: { date: '26.04.27' },
    constructionStart: '26.06.30',
  },
  {
    id: '10',
    businessType: '자체',
    siteName: '순천 선월',
    highlighted: true,
    designVE: { date: '26.03.18' },
    basicPlan: { date: '26.04.02' },
    archReview: { date: '25.05.27', highlighted: true },
    unitConfirm: { date: '25.07.25', highlighted: true },
    bizApproval: { date: '25.11.25', highlighted: true },
    designShare: { date: '26.08.31' },
    constructionStart: '26.10.31',
  },
  {
    id: '11',
    businessType: '자체',
    siteName: '울산다운 5차 B5',
    highlighted: false,
    designVE: { status: '검토중' },
    basicPlan: { date: '25.10.30' },
    archReview: { date: '26.01.16' },
    unitConfirm: { date: '26.02.28' },
    bizApproval: { date: '26.06.30' },
    designShare: { date: '25.08.31' },
    constructionStart: '26.10.31',
  },
  {
    id: '12',
    businessType: '자체',
    siteName: '구리 갈매 S1BL',
    highlighted: false,
    designVE: { status: '검토중' },
    basicPlan: { date: '24.06.20' },
    archReview: { date: '25.03.12' },
    unitConfirm: { date: '25.05.15' },
    bizApproval: { date: '26.03.31' },
    designShare: { date: '25.08.31' },
    constructionStart: '26.10.31',
  },
  {
    id: '13',
    businessType: '자체',
    siteName: '세종 5차',
    highlighted: true,
    designVE: { date: '26.04.30' },
    basicPlan: { date: '24.08.08' },
    archReview: { date: '26.02.27' },
    unitConfirm: { date: '26.04.30' },
    bizApproval: { date: '26.06.30' },
    designShare: { date: '26.09.28' },
    constructionStart: '26.11.30',
  },
  {
    id: '14',
    businessType: '도정',
    siteName: '청주사모 재개발',
    highlighted: false,
    designVE: { date: '26.05.07' },
    basicPlan: {},
    archReview: { date: '16.11.25' },
    unitConfirm: { date: '24.11.08' },
    bizApproval: { date: '24.11.08' },
    designShare: { date: '26.08.31' },
    constructionStart: '26.11.30',
  },
  {
    id: '15',
    businessType: '임대',
    siteName: '화성남양2차',
    highlighted: false,
    designVE: { status: '검토중' },
    basicPlan: { date: '19.11.01' },
    archReview: { date: '20.03.27' },
    unitConfirm: { status: '기획정' },
    bizApproval: { date: '25.06.24' },
    designShare: { date: '26.09.28' },
    constructionStart: '26.11.30',
  },
  {
    id: '16',
    businessType: '임대',
    siteName: '청주지북 1,2차',
    highlighted: false,
    designVE: { status: '검토중' },
    basicPlan: { date: '23.02.06' },
    archReview: { date: '23.09.21' },
    unitConfirm: { status: '기획정' },
    bizApproval: { date: '25.07.14' },
    designShare: { date: '26.09.28' },
    constructionStart: '26.11.30',
  },
  {
    id: '17',
    businessType: '도정',
    siteName: '포항 학잠 재개발',
    highlighted: false,
    designVE: { date: '26.06.29' },
    basicPlan: {},
    archReview: { date: '19.05.02' },
    unitConfirm: { date: '24.12.16' },
    bizApproval: { date: '21.04.13' },
    designShare: { date: '27.01.25' },
    constructionStart: '27.03.31',
  },
  {
    id: '18',
    businessType: '도정',
    siteName: '회계원 재개발',
    highlighted: false,
    designVE: { date: '26.03.30' },
    basicPlan: { date: '26.04.15' },
    archReview: { date: '22.07.13' },
    unitConfirm: { date: '26.03.31' },
    bizApproval: { date: '23.03.09' },
    designShare: { date: '27.01.25' },
    constructionStart: '27.03.31',
  },
  {
    id: '19',
    businessType: '임대',
    siteName: '광주에너지밸리',
    highlighted: false,
    designVE: { status: 'Drop 검토중' },
    basicPlan: { date: '22.04.06' },
    archReview: { date: '24.12.05' },
    unitConfirm: { status: '기획정' },
    bizApproval: { date: '25.04.08' },
    designShare: { date: '26.01.30' },
    constructionStart: '27.03.31',
  },
  {
    id: '20',
    businessType: '민간',
    siteName: '울산 무거 10BL',
    highlighted: true,
    designVE: { date: '26.04.15' },
    basicPlan: { date: '26.03.19' },
    archReview: { date: '26.07.30' },
    unitConfirm: { date: '26.09.30' },
    bizApproval: { date: '26.12.30' },
    designShare: { date: '27.03.30' },
    constructionStart: '27.05.31',
  },
  {
    id: '21',
    businessType: '공모',
    siteName: '평택 고덕 Abc-12',
    highlighted: false,
    designVE: { status: '비주관, 관여X' },
    basicPlan: {},
    archReview: {},
    unitConfirm: {},
    bizApproval: {},
    designShare: {},
    constructionStart: '26.07.31',
  },
  {
    id: '22',
    businessType: '공모',
    siteName: '평택 고덕 A-63',
    highlighted: false,
    designVE: { status: '비주관, 관여X' },
    basicPlan: {},
    archReview: {},
    unitConfirm: {},
    bizApproval: {},
    designShare: {},
    constructionStart: '26.07.31',
  },
  {
    id: '23',
    businessType: '공모',
    siteName: '평택 고덕 A-64',
    highlighted: false,
    designVE: { status: '비주관, 관여X' },
    basicPlan: {},
    archReview: {},
    unitConfirm: {},
    bizApproval: {},
    designShare: {},
    constructionStart: '26.07.31',
  },
  {
    id: '24',
    businessType: '공모',
    siteName: '평택 고덕 A-65',
    highlighted: false,
    designVE: { status: '비주관, 관여X' },
    basicPlan: {},
    archReview: {},
    unitConfirm: {},
    bizApproval: {},
    designShare: {},
    constructionStart: '26.07.31',
  },
];
